server:
  port: 8082
  address: 192.168.1.17

spring:
  app:
    jwtSecret: s3cr37
    jwtExpirationMs: 36000000

  datasource:
    # Production Database Configuration
    url: jdbc:postgresql://localhost:5432/Ticket_Sale
    username: postgres
    password: Kurama279
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    # Test Database Configuration
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
